### ISSUE TITLE
Questions about the quantization process

### ISSUE THREAD

**Issue by DangBowen-Bell** [exitudio/MMM#27]
Hello, 

Thank you for open-sourcing your code! I have a few questions regarding the quantization process:

(1) In your paper, you mentioned using factorized code to enhance codebook utilization. However, I couldn’t locate the corresponding implementation in the provided code. Could you please point me to the relevant section?

(2) While comparing your quantization process with T2M-GPT, I noticed some different lines used to adjust the codebook updates: 

```
usage = (self.code_count.view(self.nb_code, 1) >= 1.0).float()
self.usage = self.usage.to(usage.device)
if self.reset_count >= 20:
    self.reset_count = 0
    usage = (usage + self.usage >= 1.0).float()
else:
    self.reset_count += 1
    self.usage = (usage + self.usage >= 1.0).float()
    usage = torch.ones_like(self.usage, device=x.device)
code_update = self.code_sum.view(self.nb_code, self.code_dim) / self.code_count.view(self.nb_code, 1)
```

Based on my understanding, this adjustment ensures that all codes are updated and prevents updates from focusing solely on specific codes. However, I am curious about the reasoning behind setting the value to '20'. Given that the VQ-VAE training involves 300,000 iterations, could this value be too small?

Thank you in advance for your assistance. I look forward to your response!

**Comment by exitudio** [comment]
Thank you for interest in our work.
1) You can specify  ```nb_code``` and ```qcode_dim``` when training VQVAE (the default value is already 8192x32):
```
python train_vq.py --dataname t2m --exp-name vq_name --nb_code 8192 --code_dim 32
```
VQVAE is initialized [here](https://github.com/exitudio/MMM/blob/main/train_vq.py#L92)

2) T2M-GPT uses 512 codebook entries and resets unused codebook entries every iteration. We use 8192 codebook entries. If we reset the codebook every iteration, we encountered codebook collapse due to the larger codebook size. On the other hand, if we reset unused codebook entries less frequently, VQVAE may underutilize the codebook (using only a small portion of the codebook).

We performed a parameter search and found that resetting the codebook every 20 iterations yields the best quality. You can refer to ```Section C``` in the supplementary materials.
(P.S. There is nothing specific about "20"; it should be treated as a hyperparameter rather than being hardcoded.)

**Comment by DangBowen-Bell** [comment]
Thank you for your response. I’ve reviewed the supplementary materials but remain a bit unclear about the codebook reset strategy. My understanding is that in most cases (19 out of 20), 'usage' is set to all-ones, meaning the codebook only relies on the updates from the current iteration, while 'self.usage' tracks the cumulative 'usage' from previous iterations. On the 20th iteration, the codebook resets. Is this understanding correct?

After experimenting with and without this strategy, I’ve found it to be very effective for motion VQ-VAE. However, I’m uncertain whether it generalizes to other VQ-VAE models. Are there any reference codes or papers that elaborate on this strategy? Many thanks.

**Comment by DangBowen-Bell** [comment]
Thank you for the detailed explanation. My question has been solved.
